# coding: utf-8

LEAVES = {0: {0: 'Arensfelde',
              1: 'Spandau',
              2: 'Ostbahnhof',
              3: 'Potsdam Hbf'},
          1: {0: 'S1',
              1: 'S2',
              2: '',
              3: 'S5',
              4: None,
              5: 'S7'},
          2: {0: 'über Ostbahnhof, Wahrschauer Straße',
              1: 'Kurzzug hält vorn',
              2: 'Mit dem Fahrad nich in\' ersten Wagen!'},
          3: {0: 'Arensfelde',
              1: 'Spandau',
              2: 'Ostbahnhof',
              3: 'Potsdam Hbf'},
          4: {0: 'S1',
              1: 'S2',
              2: '',
              3: 'S5',
              4: None,
              5: 'S7'},
          5: {0: 'über Ostbahnhof, Wahrschauer Straße',
              1: 'Kurzzug hält vorn',
              2: 'Mit dem Fahrad nich in\' ersten Wagen!'}}
