# coding: utf-8

LEAFS = {'destLeft': {0: 'Arensfelde',
                      1: 'Spandau',
                      2: 'Ostbahnhof',
                      3: 'Potsdam Hbf'},
         'lineLeft': {0: 'S1',
                      1: 'S2',
                      2: '',
                      3: 'S5',
                      4: None,
                      5: 'S7'},
         'descLeft': {0: 'über Ostbahnhof, Wahrschauer Straße',
                      1: 'Kurzzug hält vorn',
                      2: 'Mit dem Fahrad nich in\' ersten Wagen!'},
         'destRight': {0: 'Arensfelde',
                       1: 'Spandau',
                       2: 'Ostbahnhof',
                       3: 'Potsdam Hbf'},
         'lineRight': {0: 'S1',
                       1: 'S2',
                       2: '',
                       3: 'S5',
                       4: None,
                       5: 'S7'},
         'descRight': {0: 'über Ostbahnhof, Wahrschauer Straße',
                       1: 'Kurzzug hält vorn',
                       2: 'Mit dem Fahrad nich in\' ersten Wagen!'}}
